source "https://rubygems.org"

gem 'rails', '~> 7.2.1'
gem "puma", ">= 5.0"
gem "tzinfo-data", platforms: %i[windows jruby]
gem "bootsnap", require: false
gem "rack-cors"
gem "msgpack"

gem 'rswag-api'
gem 'rswag-ui'
gem 'moji'

group :development, :test do
  gem "rspec-rails"
  gem "factory_bot_rails"
  gem "debug", platforms: %i[mri windows], require: "debug/prelude"
  gem "brakeman", require: false
  gem "rubocop-rails-omakase", require: false
  gem 'rswag-specs'
end